authcustom/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import login_view

urlpatterns = [
    path('', login_view, name='login_view'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

restapi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from authcustom.api import viewsets as v

# swagger
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'users', v.UserViewSet, basename='users')

swagger_urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns = [
    path('', include('authcustom.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
] + swagger_urlpatterns

authcustom/forms.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={})
    )
    password = forms.CharField(
        required=True,
        min_length=6,
        widget=forms.PasswordInput(
            attrs={})
    )

authcustom/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from authcustom.forms import LoginForm


@csrf_protect
def login_view(request):
    form = LoginForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    login(request, user)
            else:
                msg_error = 'Usuário e senha não conferem.'
                messages.error(request, msg_error)

    return render(request, 'authcustom/login.html', {'form': form})

authcustom/templates/authcustom/base.html
{% load static %}
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %} - APP</title>
  <link rel="stylesheet" type="text/css" href="{% static 'authcustom/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'authcustom/css/base.css' %}">

  {% block head %}
  {% endblock %}

  {% block style %}
  {% endblock %}
</head>

<body>
  <nav class="navbar fixed-top navbar-light" style="background-color: #abc7dc;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'users-list' %}">API</a>

      {% block navitens %}
      {% endblock %}

    </div>
  </nav>
  <div style="margin-bottom:200px">

    {% block content %}
    {% endblock %}

  </div>
  <nav class="fixed-bottom text-center text-muted" style="font-size:0.9rem">
    <div class="container" style="border-top: 1px #ccc solid; padding:10px; background-color: #f5f5f5;">
      <span>&copy; {% now "Y" %}</span>
    </div>
  </nav>
  <script src="{% static 'authcustom/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'authcustom/js/popper.min.js' %}"></script>
  <script src="{% static 'authcustom/js/bootstrap.js' %}"></script>
  <script src="{% static 'authcustom/js/ajax-setup.js' %}"></script>

  {% block js %}
  {% endblock %}
</body>
</html>

authcustom/templates/authcustom/login.html
{% extends "authcustom/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static 'authcustom/css/style.css' %}">
{% endblock %}

{% block navitens %}
  {% if user.is_authenticated %}
    <a href="{% url 'logout' %}" class='btn btn-danger btn-sm' style="border-radius: 20px; padding: 0.175rem 1.25rem;">LOGOUT</a>
  {% else %}
    <a href="." class='btn btn-primary' style="border-radius: 20px; padding: 0.375rem 1.75rem;">SIGN UP</a>
  {% endif %}
{% endblock %}

{% block content %}
<div class="text-center" style="margin-top:40px">
  {% if user.is_authenticated %}
    <h1 class="h3 font-weight-normal">You are logged in <span class="text-info">{{ user.first_name }}</span></h1>

  {% else %}
    <form id="form" class="form" method="post">
      
      {% csrf_token %}
      
      <h1 class="h3 font-weight-normal">LOGIN</h1>

      {% for message in messages %}
        <p id="alert" class="alert alert-danger" role="alert">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <span style="font-weight:bold">{{ message }}</span>
        </p>
      {% endfor %}

      {{ form.errors }}

      <label for="id_email" class="sr-only">Your Professional Email</label>
      {% render_field form.email class+="form-control no-border-bottom-radius" placeholder="Your Email" %}

      <label for="id_password" class="sr-only">Password</label>
      {% render_field form.password class+="form-control no-border-top-radius" placeholder="Your Password" style="margin-bottom:10px" %}
      
      <button class="btn btn-lg btn-success btn-block" type="submit" name="login">Login</button>
    </form>
  {% endif %}
</div>
{% endblock %}

{% block js %}
  <script>
  console.log('ok');
    window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
      });
    }, 3000);
  </script>
{% endblock %}